### ISSUE TITLE
How to minify .js on save?

### ISSUE THREAD

**Issue by MDBenson** [refgd/easy-complie#1]
Hi,

You don't give any details of settings for automatically minifying .js on save. Can you give some details on how to set up output paths etc as there's nothing inthe docs and it doesn't seem to work for me at the moment.

Thanks

**Comment by refgd** [comment]
There is no minify on save, you have to run manually. auto minify only work for compile. I can add this feature on next version.

**Comment by Zaczero** [comment]
+1

**Comment by featuriz** [comment]
I'm waiting.
I can contribute, If I know how to do the things. I'm new vsc.

**Comment by refgd** [comment]
Updated.
use config to enable minify on save, use ignore to ignore files
```
"easycompile.compile": {
        "minifyJsOnSave": true,
        "minifyCssOnSave": true,
        "ignore" : [
              "**/test/*.js"
         ]
}
```
