### ISSUE TITLE
Integrate sass2less (plugin for LESS)

### ISSUE THREAD

**Issue by Jany-M** [refgd/easy-complie#12]
I was wondering if you could integrate [this](https://github.com/mediafreakch/less-plugin-sass2less) awesome plugin for LESS.
It allows to import an `scss` into a `less` as reference, or convert an `scss` to `less`.

It's one of a kind and it would make a lot of people happy.
Please? :1st_place_medal:

**Comment by refgd** [comment]
integrated. default enabled. To disable it:
```
"easycompile.less":{
        "sass2less": false   
}
```

**Comment by Jany-M** [comment]
Thank you!!!!
