### ISSUE TITLE
SCSS compiles import files

### ISSUE THREAD

**Issue by cpgb85** [refgd/easy-complie#14]
I have multiple files i am importing into 1 scss document.  Typically they don't build if you name them like this: "_header.scss".  But when i edit it, it compiles.  Anything i reference in the main SCSS file should not compile on it's own.

**Comment by refgd** [comment]
There have two way to do this.
1. Use main option: Compiles a different file instead of this one.
```
// main: ../main.scss
.feature {
}
```

2. Use ignore setting
```
"easycompile.compile": {
    "ignore" : [
        "**/_*.scss"
    ]
}
```

**Comment by cpgb85** [comment]
The first option isn't descriptive. Nor do you have documentation for it. Can we get some guides on how to use it?

**Comment by cpgb85** [comment]
Figured it out. Thanks for the help!
