### ISSUE TITLE
@set and each() throwing errors

### ISSUE THREAD

**Issue by Jany-M** [refgd/easy-complie#15]
As per `LESS` documentation, [this](http://lesscss.org/functions/#list-functions-each) is correct:

`
@set: {
    one: blue;
    two: green;
    three: red;
}
.set {
    each(@set, {
      @{key}-@{index}: @value;
    });
}
`

However, it won't compile.

![capture](https://user-images.githubusercontent.com/4365842/44559807-a2791f00-a74c-11e8-94a8-bbfbad307ac2.PNG)

This doesn't either:

`.set-2() {
  one: blue;
  two: green;
  three: red;
}
.set-2 {
  // Call mixin and iterate each rule
  each(.set-2(), .(@v, @k, @i) {
    @{k}-@{i}: @v;
  });
}`

Are all `LESS` functions covered in the compiler?

**Comment by refgd** [comment]
Fixed. Upgrade the less compiler to the newest.

**Comment by Jany-M** [comment]
Thank you!!!
