### ISSUE TITLE
SCSS File not found when importing a partial with @import element

### ISSUE THREAD

**Issue by aeizenlee** [refgd/easy-complie#16]
This is my folder structure

--/styles
---/helpers/
-----/_mixins.scss
-----/_variables.scss
-----/_helpers.scss
---style.scss

- style.scss
// out: ../../style.css, sourceMap: true, autoprefixer: > 1%; last 1 versions, groupmedia: true
@import "helpers/helpers"

- _helpers.scss
@import "mixins";
@import "variables";

please help. Thank you!

**Comment by minkir014** [comment]
What do you mean with not found??

**Comment by refgd** [comment]
Close, may fix in [2bc41c05249056201c8dd0196520d18a121978e1]
