### ISSUE TITLE
Problems with "ignore" path

### ISSUE THREAD

**Issue by joesawa** [refgd/easy-complie#17]
Hello, I'm having a pretty annoying problem with the "ignore" feature.

It seems to act as either _ignore everything_ or _ignore nothing._

I've tried a ton of different paths, to no avail. Every single one I try will ignore everything. As soon as I remove the entire setting, it compiles everything again. 

```
"easycompile.compile": {
    "ignore": [ -filepath- ]
},
```

I'm on a Mac, trying to ignore all files within a specific folder. Project tree is essentially this:

```
.vscode
    settings.json
wp-content
    themes
        theme-folder
            assets
                scss-folder-1
                scss-folder-2  <--
```

I want to ignore all .scss files in **scss-folder-2** including all files in subfolders.

Am I doing something wrong? I've tried to use the "ignore" setting in workspace settings or user settings, neither of which made a difference in my problem.

**Comment by refgd** [comment]
All "scss" files in folder "scss-folder-2" not including sub folders.
`"easycompile.compile": {
        "ignore" : [
            "**/scss-folder-2/*.scss"
        ]
    }`

All "scss" files in folder "scss-folder-2" and including sub folders.
`"easycompile.compile": {
        "ignore" : [
            "**/scss-folder-2/**/*.scss"
        ]
    }`
