### ISSUE TITLE
@import not finding sass partials

### ISSUE THREAD

**Issue by sebastiencyr** [refgd/easy-complie#2]
Hi,

Compile is failing on imported scss files which begin with "_" without specifying it.

Ex.: bootstrap4

bootstrap.scss (@import "variables")
|____   \_variables.scss (file not found)
|____   \_ex....

**Comment by masiorama** [comment]
I have the same problem. Is this going to be fixed?

**Comment by refgd** [comment]
This problem should be fixed already. You can update from the market.

**Comment by masiorama** [comment]
I already have the latest version.
I'm using composer, and loading the styles in a custom scss

`scss/styles.scss`

 including them this way:

`@import "../vendor/twbs/bootstrap/scss/bootstrap.scss"; `

The vendor directory is at the same level as my custom scss directory.

Am I maybe importing in the wrong way?
Thanks in advance.

**Comment by refgd** [comment]
@masiorama Sorry, I just got time to fix this bug. I updated. Please try the new version. 
Fix at 3a8a79bb42432bd082b285d48f5c5cb8afe36ab6

**Comment by masiorama** [comment]
@refgd hello, thanks but it still seems not working for me.
