### ISSUE TITLE
minifyJsOnSave to a new .min file?

### ISSUE THREAD

**Issue by danwebbBC** [refgd/easy-complie#20]
I'm new to a lot of this compiling stuff so I'm probably missing something.

When this extension minifies, it does it on the same JS file and overwrites it, which is super-scary!  Other minifiers I've used create a new .min file so that the original is still readable for developing.

In this extension, is there a way to make it minify JS to a different file?  Attached is a screenshot showing how I'm trying to edit the settings.json in Visual Studio Code.  Thanks!

![capture](https://user-images.githubusercontent.com/24482705/52501251-c1515d80-2b94-11e9-8b52-d6a176062192.PNG)

**Comment by refgd** [comment]
you can change ".js" extension to ".ts", and set outdir with compress.
the extension will minify the files to the out folder.
