### ISSUE TITLE
Save All not compiling LESS to CSS when saving all file changes from a different file

### ISSUE THREAD

**Issue by thenetta101** [refgd/easy-complie#21]
If I am not on the LESS file that I made changes to when I choose to "save all", it does not compile my changes to the css file. When I choose to save all when I am on the LESS file it does work. I receive an error message if I am not on a less file than needs to be compiled to css, when I "save all".

**Comment by thenetta101** [comment]
![screen shot 2019-02-27 at 9 17 00 am](https://user-images.githubusercontent.com/29393326/53502351-8182e500-3a73-11e9-80c5-23569f0e1aa9.png)

**Comment by refgd** [comment]
This extension not handle "save all" function, it's too heavy.
