### ISSUE TITLE
.css files missing configuration properties/options

### ISSUE THREAD

**Issue by mountainash** [refgd/easy-complie#26]
I have a few projects which are using plain ol' .css, yet with `"minifyCssOnSave": true` at my VSCode user settings level, saving a .css file results in the source file minimising. It would be nice to be able to set the location for the minimised file (either through inline [line 1] comment configs, or though the workspace vscode `settings.json`. eg:

```json
	"easycompile.css": {
		"out": "./screen.min.css",
		/*OR "outExt": ".min.css"*/
	},
```

[Location in Code](https://github.com/refgd/easy-complie/blob/ad85542f5b626ea449ab5146c470d455f2109942/package.json#L100)

**Comment by refgd** [comment]
you can just change the ".css" to ".less", you don't need change any code. even more, you can merge multi css file into one, just change the extension to "less".

**Comment by mountainash** [comment]
That's definitely a work around that could work (might look confusing to other team members working on the same project).

The `README` documentation should be updated then as it currently reads like all the same options work for all CSS file formats.

**Comment by refgd** [comment]
Add configuration for minify JS/CSS, detail see [README](https://github.com/refgd/easy-complie#extension-settings)
