### ISSUE TITLE
The word "define" prepended to minified Javascript files

### ISSUE THREAD

**Issue by markvreeland** [refgd/easy-complie#27]
Source file: "custom.js"

$(document).ready(function() {
});

Output file: "custom.min.js"

define,$(document).ready(function(){});

Where is this coming from?

**Comment by refgd** [comment]
looking here [README](https://github.com/refgd/easy-complie#extension-settings)
```
easycompile.js {
...  
"surround": { string }  
...  
}
```

**Comment by markvreeland** [comment]
Thank you. May I recommend that the default value be changed to "" rather than "(function (define){ ${code} })(define)"
