### ISSUE TITLE
Extension not found

### ISSUE THREAD

**Issue by gustavwilliam** [refgd/easy-complie#38]
I've been using this extension for VS Code on my Mac for a while now. However, I can't find it on my computer running Manjaro KDE.

When following the install instructions, the top alternative when viewing VSC extensions is "Live Sass Compiler", and not "Easy Compile". I can't find it on the rest of the list either.

Do you know what's happening here? Has the extension been removed, or is something strange up? I can't find any other issues with my system.

**Comment by refgd** [comment]
I think it is still in Marketplace, may be you can try just search "Easy Compile",
The Marketplace link is: https://marketplace.visualstudio.com/items?itemName=refgd.easy-compile
