### ISSUE TITLE
New version 1.2.3 doesn't work for scss

### ISSUE THREAD

**Issue by posel** [refgd/easy-complie#42]
Whenever I try to save scss file, VSC fails with error  "unable to resolve resource" file. Tried with several scss file but everything failed.

I have returned to the former version 1.2.1 and it works correctly, so that the problem is definitely in the new version.

VSC is in the latest version and npm was updated last week so that everything is new. I use 
// out:....
// main:...
definition at the first line of the scss documents but saving failed even on files without the definition where to save the css file.

**Comment by yuvalsabar** [comment]
I have the same issue.

**Comment by hilsojunior** [comment]
Less files also stopped compiling.

**Comment by posel** [comment]
Yes, it already works as before.
Thanks.
