### ISSUE TITLE
Failure to pickup new variables from @import files

### ISSUE THREAD

**Issue by MDBenson** [refgd/easy-complie#5]
I am using a **@import _vars.scss** file into my **main.scss** to set various values. On 2 occasions now I have set new vars in the **_vars.scss** and the **main.scss** has failed to compile stating 'Undefined variable' when it's clearly defined and other vars in the from the **_vars.scss** import work okay and are found.

The only workaround I found was to remname the **_vars.scss** which presumably registered as a new file and was read successfully.

**Comment by refgd** [comment]
I tried and did find the bug, whatever I fix the bug #9 , may be fixed your bug too.
