### ISSUE TITLE
Cannot find @import files when compiling scss

### ISSUE THREAD

**Issue by MDBenson** [refgd/easy-complie#6]
I suspect this is related to #5 but as the issue is different I split them up.

I added the bootstrap source scss to my file structure and attempted to **@import** the **_mixins.scss** via:
``@import '../bootstrap/_mixins.scss';``

into my **main.scss**. Easy Compile throws an error and cannot find the file, reporting:
``File "c:\c\Users\MD\Documents\GitHub\projectX\sass\bootstrap" not found``

As I am on Windows I can see this may be a path issue? That looks like a Cygwin-style UNIX patch that's got a  c:\ stuck on the beginning somehow?

The directory structure is:

- projectX
    - sass
         - bootstrap <-- bootstrap lives here
              - mixins (dir)
              - _mixins.scss
         - css
              - main.scss
         - lib 
            - _mixins.scss
            - _vars.scss

**Comment by MDBenson** [comment]
Subsequent to this, bootstrap will not compile from source at all, Easy compile is not correctly able to parse the paths apparently from their **@import** statements (e.g. **@import "jumbotron";** ) which are supposed to pick up files in the same folder. Parser reports:
``File "c:\Users\MD\Documents\GitHub\sass\bootstrap" not found``  <<== this is missing the **projectX** folder name, so it's got confused totally.

**Comment by MDBenson** [comment]
More info:

If I restate the import as:

``@import '../bootstrap/mixins';``

Easy Compile states there are two alternatives (which is correct):
``
It's not clear which file to import for '@import "../bootstrap/mixins"'.
Candidates:
  ../bootstrap/mixins
  ../bootstrap/_mixins.scss
Please delete or rename all but one of these files.
``
From this it is clear that is is resolving the path correctly in this instance and correctly sees ambiguous alternatives... yet if I reference the ../bootstrap/_mixins.scss file drectly it cannot find it.

**Comment by MDBenson** [comment]
I have just run in to this again with a .less file. It is ONLY happening when I add the third line with the include on (sidebr.less). If I remove that it compiles normally, finding the file it supposedly cannot fine here.

Suffice to say the file is not at the directoy it's trying to access  in that error.  The obscured path shown is the project root folder, btw.

![compileless error](https://user-images.githubusercontent.com/4146140/43648571-acebfd74-9732-11e8-8594-eb7667961c0f.PNG)

**Comment by refgd** [comment]
Close, may fix in [2bc41c05249056201c8dd0196520d18a121978e1]
